import '../workout_list.dart';

List<Workout> armDay1 = [
  jumpingJacks,
  sideArmRaise,
  tricepsDips,
  armCircleClockWise,
  armCircleCounterClockWise,
  diamond,
  sideArmRaise2,
  bodySaw,
  diagonalPlank,
  punches,
  pushUps,
  tricepsStretchLeft,
  tricepsStretchRight,
  standingBicepsStretchLeft,
  standingBicepsStretchRight
];
List<Workout> armDay2 = [
  jumpingJacks,
  sideArmRaise,
  tricepsDips,
  armCircleClockWise,
  armCircleCounterClockWise,
  diamond,
  sideArmRaise2,
  bodySaw,
  diagonalPlank,
  punches,
  pushUps,
  tricepsStretchLeft,
  tricepsStretchRight,
  standingBicepsStretchLeft,
  standingBicepsStretchRight
];
List<Workout> armDay3 = [
  jumpingJacks,
  sideArmRaise,
  tricepsDips,
  armCircleClockWise,
  armCircleCounterClockWise,
  diamond,
  sideArmRaise2,
  diagonalPlank,
  punches,
  pushUps,
  tricepsStretchLeft,
  tricepsStretchRight,
  standingBicepsStretchLeft,
  standingBicepsStretchRight
];
List<Workout> armDay4 = [
  jumpingJacks,
  sideArmRaise,
  tricepsDips,
  armCircleClockWise,
  armCircleCounterClockWise,
  diamond,
  sideArmRaise2,
  diagonalPlank,
  punches,
  pushUps,
  tricepsStretchLeft,
  tricepsStretchRight,
  standingBicepsStretchLeft,
  standingBicepsStretchRight
];
List<Workout> armDay5 = [
  jumpingJacks,
  armCircleClockWise,
  rhomboidPulls,
  sideArmRaise,
  kneePushUps,
  reclinedRhomboidSqueezes,
  threadTheNeedleL,
  threadTheNeedleR,
  armScissors,
  rhomboidPulls2,
  sideArmRaise2,
  kneePushUps2,
  catCowPose,
  reclinedRhomboidSqueezes2,
  childPose,
];
List<Workout> armDay6 = [
  jumpingJacks,
  armCircleClockWise,
  rhomboidPulls,
  sideArmRaise,
  kneePushUps,
  reclinedRhomboidSqueezes,
  threadTheNeedleL,
  threadTheNeedleR,
  armScissors,
  rhomboidPulls2,
  sideArmRaise2,
  kneePushUps2,
  catCowPose,
  reclinedRhomboidSqueezes2,
  childPose,
];
List<Workout> armDay7 = []; //rest
List<Workout> armDay8 = [...shoulderBeginner];
List<Workout> armDay9 = [...shoulderBeginner];
List<Workout> armDay10 = [...armsBeginner];
List<Workout> armDay11 = [...armsBeginner];
List<Workout> armDay12 = [
  jumpingJacks,
  tricepsDips,
  inclinePushUps,
  rhomboidPulls,
  floorTricepsDips,
  catCowPose,
  diamond2,
  inclinePushUps2,
  floorTricepsDips2,
  threadTheNeedleL,
  threadTheNeedleR,
  inchWorm,
  pulseUp2,
  childPose,
];
List<Workout> armDay13 = [
  jumpingJacks,
  tricepsDips,
  inclinePushUps,
  rhomboidPulls,
  floorTricepsDips,
  catCowPose,
  diamond2,
  inclinePushUps2,
  floorTricepsDips2,
  threadTheNeedleL,
  threadTheNeedleR,
  inchWorm,
  pulseUp2,
  childPose,
];
List<Workout> armDay14 = []; //rest
List<Workout> armDay15 = [
  jumpingJacks,
  tricepsDips,
  inclinePushUps,
  rhomboidPulls,
  floorTricepsDips,
  catCowPose,
  diamond2,
  inclinePushUps2,
  floorTricepsDips2,
  threadTheNeedleL,
  threadTheNeedleR,
  pulseUp2,
  childPose,
];
List<Workout> armDay16 = [
  armCircleClockWise,
  armCircleCounterClockWise,
  tricepsPushUp,
  floorTricepsDips,
  punches,
  pushUpsRotation,
  armCurlsCrunchLeft,
  armCurlsCrunchRight,
  floorTricepsDips2,
  tricepsPushUp2,
  pushUpsRotation2,
  armCurlsCrunchLeft,
  armCurlsCrunchRight,
  skippingWithOutRope,
  pushUps,
  burpee,
  armScissors,
  skippingWithOutRope,
  tricepsStretchLeft,
  tricepsStretchRight,
  standingBicepsStretchLeft,
  standingBicepsStretchRight,
];
List<Workout> armDay17 = [
  armCircleClockWise,
  armCircleCounterClockWise,
  tricepsPushUp,
  floorTricepsDips,
  punches,
  pushUpsRotation,
  armCurlsCrunchLeft,
  armCurlsCrunchRight,
  floorTricepsDips2,
  tricepsPushUp2,
  pushUpsRotation2,
  armCurlsCrunchLeft,
  armCurlsCrunchRight,
  skippingWithOutRope,
  pushUps,
  burpee,
  armScissors,
  skippingWithOutRope,
  tricepsStretchLeft,
  tricepsStretchRight,
  standingBicepsStretchLeft,
  standingBicepsStretchRight,
];
List<Workout> armDay18 = [
  armCircleClockWise,
  armCircleCounterClockWise,
  tricepsPushUp,
  floorTricepsDips,
  punches,
  pushUpsRotation,
  armCurlsCrunchLeft,
  armCurlsCrunchRight,
  floorTricepsDips2,
  tricepsPushUp2,
  pushUpsRotation2,
  armCurlsCrunchLeft,
  armCurlsCrunchRight,
  burpee,
  armScissors,
  skippingWithOutRope,
  tricepsStretchLeft,
  tricepsStretchRight,
  standingBicepsStretchLeft,
  standingBicepsStretchRight,
];
List<Workout> armDay19 = [...shoulderIntermediate];
List<Workout> armDay20 = [...armsIntermediate];
List<Workout> armDay21 = []; //rest
List<Workout> armDay22 = [...shoulderIntermediate];
List<Workout> armDay23 = [...armsIntermediate];
List<Workout> armDay24 = [...shoulderAdvance];
List<Workout> armDay25 = [...shoulderAdvance];
List<Workout> armDay26 = [...armsAdvance];
List<Workout> armDay27 = [...armsAdvance];
List<Workout> armDay28 = []; //rest

List<List<Workout>> armChallenges = [
  armDay1,
  armDay2,
  armDay3,
  armDay4,
  armDay5,
  armDay6,
  armDay7,
  armDay8,
  armDay9,
  armDay10,
  armDay11,
  armDay12,
  armDay13,
  armDay14,
  armDay15,
  armDay16,
  armDay17,
  armDay18,
  armDay19,
  armDay20,
  armDay21,
  armDay22,
  armDay23,
  armDay24,
  armDay25,
  armDay26,
  armDay27,
  armDay28,
];
