import '../../enums/workout_type.dart';
import '../../models/explore_workout_model.dart';
import '../workout_list.dart';

List<ExploreWorkout> weekdayWorkoutList = [
  ExploreWorkout(
      title: "Monday Workout Challenge",
      imgSrc: "assets/explore_image/img_2.jpg",
      workoutType: WorkoutType.Intermediate,
      description: [],
      workoutList: _mondayWorkout),
  ExploreWorkout(
      title: "Tuesday Workout Challenge",
      imgSrc: "assets/explore_image/img_12.jpg",
      workoutType: WorkoutType.Beginner,
      description: ["Weekly workout plan provide exercises for different mussels group In order to acchive your fitness goal"],
      workoutList: _tuesdayWorkout),
  ExploreWorkout(
      title: "Wednesday Workout Challenge",
      imgSrc: "assets/explore_image/img_8.jpg",
      workoutType: WorkoutType.Intermediate,
      description: [],
      workoutList: _wednesdayWorkout),
  ExploreWorkout(
      title: "Thursday Workout Challenge",
      imgSrc: "assets/explore_image/img_13.jpg",
      workoutType: WorkoutType.Beginner,
      description: [], workoutList: _thursdayWorkout),
  ExploreWorkout(
      title: "Friday Workout Challenge",
      imgSrc: "assets/explore_image/img_14.jpg",
      workoutType: WorkoutType.Advance,
      description: [],
      workoutList: _fridayWorkout),
  ExploreWorkout(
      title: "Saturday Workout Challenge",
      imgSrc: "assets/explore_image/img_15.jpg",
      workoutType: WorkoutType.Intermediate,
      description:[],  workoutList: _saturdayWorkout),
  ExploreWorkout(
      title: "Sunday Workout Challenge",
      imgSrc: "assets/explore_image/img_16.jpg",
      workoutType: WorkoutType.Beginner,
      description: [],
      workoutList: _sundayWorkout),
];

List<Workout> _mondayWorkout = [
  jumpingJacks,
  armCircleClockWise,
  pushUps,
  wideArmPushUps,
  hinduPushUps,
  staggeredPushUps,
  pushUpsRotation,
  pushUps2,
  hinduPushUps2,
  staggeredPushUps2,
  pushUpsRotation2,
  declinePushUps,
  walkingPlank,
  cobraStretch,
  chestStretch
];
List<Workout> _tuesdayWorkout = [
  jumpingJacks,
  pushUps,
  wallUp,
  abdominalCrunches,
  walkingLunges,
  squats,
  tricepsDipsChest2,
  elbowPlanks,
  flutterKikes2,
  pushUpsRotation,
  sidePlankLeft,
  sidePlankRight,
  cobraStretch,
];
List<Workout> _wednesdayWorkout = [
  jumpingJacks,
  reverseCrunches,
  mountainClimbing,
  buttBridge,
  abdominalCrunches,
  russianTwist,
  vUps,
  diagonalPlank,
  sidePlankRight,
  sidePlankLeft,
  russianTwist2,
  buttBridge2,
  diagonalPlank2,
  reverseCrunches2,
  vUps2,
  abdominalCrunches2,
  sidePlankRight2,
  sidePlankLeft2,
  cobraStretch,
  spineLumberL,
  spineLumberR,
];
List<Workout> _thursdayWorkout = [
  jumpingJacks,
  benchDips,
  inclinePushUps,
  rhomboidPulls,
  floorTricepsDips,
  catCowPose,
  diamond2,
  inclinePushUps2,
  plankUp,
  sideArmRaise,
  floorTricepsDips2,
  sidePlankRight,
  sidePlankLeft,
  inchWorm,
  threadTheNeedleL,
  threadTheNeedleR,
  childPose,
];
List<Workout> _fridayWorkout = [
  jumpingJacks,
  squats,
  squats,
  squats,
  bottomLegLiftLeft,
  bottomLegLiftRight,
  bottomLegLiftLeft,
  bottomLegLiftRight,
  bottomLegLiftLeft,
  bottomLegLiftRight,
  lateralSquat,
  lateralSquat,
  buttBridge,
  buttBridge,
  buttBridge,
  sumoSquat,
  sumoSquat,
  fireHydrantLeft,
  fireHydrantRight,
  fireHydrantLeft,
  fireHydrantRight,
  quadStretchLeft,
  quadStretchright,
  lyingButterFlyStretch,
  walkingLunges,
  walkingLunges,
  walkingLunges,
  wallResistingSingleLegLeft,
  wallResistingSingleLegRight,
  wallResistingSingleLegLeft,
  wallResistingSingleLegRight,
  calfStretchLeft,
  calfStretchRight
];
List<Workout> _saturdayWorkout = [
  armCircleClockWise,
  armCircleCounterClockWise,
  tricepsPushUp,
  floorTricepsDips,
  punches,
  pushUpsRotation,
  armCurlsCrunchLeft,
  armCurlsCrunchRight,
  floorTricepsDips2,
  tricepsPushUp2,
  pushUpsRotation2,
  armCurlsCrunchLeft,
  armCurlsCrunchRight,
  skippingWithOutRope,
  pushUps,
  burpee,
  armScissors,
  skippingWithOutRope,
  pushUps2,
  burpee,
  tricepsStretchLeft,
  tricepsStretchRight,
  standingBicepsStretchLeft,
  standingBicepsStretchRight,
];
List<Workout> _sundayWorkout = [
  armCircleClockWise,
  armCircleCounterClockWise,
  shoulderStretch,
  tricepsStretchLeft,
  tricepsStretchRight,
  chestStretch,
  kneeToChestStretch,
  calfStretchLeft,
  calfStretchRight,
  spineLumberL,
  spineLumberR,
  childPose,
  cobraStretch,
];
