class QModel {
  final String quote;
  final String author;

  QModel({required this.author, required this.quote});

  
}
List<QModel> quotesList =[
  QModel(author:"Muhammad Ali",quote:"I hated every minute of training, but I said, Don’t quit. Suffer now and live the rest of your life as a champion." ),
  QModel(author:"Aristotele",quote:"We are what we repeatedly do. Excellence then is not an act but a habit." ),
  QModel(author:"Napoleon Hill",quote:"The body achieves what the mind believes." ),
  QModel(author:"Dana Vollmer",quote:"The hard days are the best because that’s when champions are made, so if you push through, you can push through anything." ),
  QModel(author:"Arnold Schwarzenegger",quote:"If you don’t find the time, if you don’t do the work, you don’t get the results." ),
  QModel(author:"Akash",quote:"Dead last finish is greater than did not finish, which trumps did not start." ),
  QModel(author:"Vincent Williams Sr.",quote:"Push harder than yesterday if you want a different tomorrow." ),
  QModel(author:"Ronnie Coleman",quote:"The real workout starts when you want to stop." ),
  QModel(author:"Jim Rohn",quote:"Take care of your body. It’s the only place you have to live." ),
  QModel(author:"Michael Jordan",quote:"I’ve failed over and over again in my life and that is why I succeed." ),
  QModel(author:"Erin Gray",quote:"Once you are exercising regularly, the hardest thing is to stop it." ),
  QModel(author:"Mark Twain",quote:"The secret of getting ahead is getting started." ),
  QModel(author:"Gene Tunney",quote:"Exercise should be regarded as tribute to the heart" ),
  QModel(author:"Joe Mangianello",quote:"You’re going to have to let it hurt. Let it suck. The harder you work, the better you will look. Your appearance isn’t parallel to how heavy you lift, it’s parallel to how hard you work." ),
  QModel(author:"Vince Lombardi",quote:"Most people fail, not because of lack of desire, but, because of lack of commitment." ),
  QModel(author:"Wayne Gretzky",quote:"You miss one hundred percent of the shots you don’t take." ),
  QModel(author:"Dwayne Johnson",quote:"If something stands between you and your success, move it. Never be denied." ),
  QModel(author:"Michael John Bobak",quote:"All progress takes place outside the comfort zone." ),
  QModel(author:"Venus Williams quote serena williams",quote:"Just believe in yourself. Even if you don’t, just pretend that you do and at some point, you will." ),
  QModel(author:"Carli Lloyd",quote:"The harder you work and the more prepared you are for something, you’re going to be able to persevere through anything." ),
  QModel(author:"Rafael Nadal",quote:"Enduring means accepting. Accepting things as they are and not as you would wish them to be, and then looking ahead, not behind." ),
  QModel(author:"Thomas Jefferson",quote:"If you want something you’ve never had, you must be willing to do something you’ve never done." ),
  QModel(author:"Arnold Schwarzenegger",quote:"The resistance that you fight physically in the gym and the resistance that you fight in life can only build a strong character." ),
  QModel(author:"Mark Twain",quote:"Continuous improvement is better than delayed perfection." ),
  QModel(author:"Vince Lombardi",quote:"Once you learn to quit, it becomes a habit." ),
  QModel(author:"Babe Ruth",quote:"It’s hard to beat a person who never gives up." ),
  QModel(author:"Sean Patrick Flanery",quote:"Do something today that your future self will thank you for." ),
  QModel(author:"Sylvester Stallone",quote:"Success is usually the culmination of controlling failure." ),
  QModel(author:"Akash",quote:"Think of your workouts as important meetings you schedule with yourself. Bosses don’t cancel" ),
  QModel(author:"Invajy",quote:"Workout till you feel that pain and soreness in muscles. This one is good pain. No pain, no gain." ),
  QModel(author:"Robert Kiyosaki",quote:"Confidence comes from discipline and training." ),
  QModel(author:"Muhammad Ali",quote:"I don’t count my sit-ups. I only start counting when it starts hurting because they’re the only ones that count." ),
  QModel(author:"Jay Cutler",quote:"What hurts today makes you stronger tomorrow" ),
  QModel(author:"Mahatma Gandhi",quote:"Strength does not come from physical capacity. It comes from an indomitable will" ),
  QModel(author:"Michael Jordan",quote:"You must expect things of yourself before you can do them." ),
  QModel(author:"Arnold Schwarzenegger",quote:"The last three or four reps is what makes the muscle grow. This area of pain divides a champion from someone who is not a champion." ),
  QModel(author:"Mark Spitz",quote:"If you fail to prepare, you’re prepared to fail." ),
  QModel(author:"Jim Ryun",quote:"Motivation is what gets you started. Habit is what keeps you going." ),
  QModel(author:"Jack Dempsey",quote:"A champion is someone who gets up when they can’t." ),
  QModel(author:"Tommy Lasorda",quote:"The difference between the impossible and the possible lies in a person’s determination." ),
  QModel(author:"LL Cool Jgym quote",quote:"When you have a clear vision of your goal, it’s easier to take the first step toward it." ),
  QModel(author:"Michael Phelps",quote:"When I feel tired, I just think about how great I will feel once I finally reach my goal." ),
  QModel(author:"Kai Greene",quote:"You have to think about it before you can do it. The mind is what makes it all possible." ),
  QModel(author:"Akash",quote:"The only bad workout is the one that didn’t happen." ),
  QModel(author:"LeBron James",quote:"Don’t be afraid of failure. This is the way to succeed." ),
  QModel(author:"Marnelli Dimzon",quote:"You should never stay at the same level. Always push yourself to the next." ),
  QModel(author:"Robin Arzon",quote:"You did not wake up today to be mediocre." ),
  QModel(author:"Pablo Picasso",quote:"Action is the foundational key to all success." ),
  QModel(author:"Fred DeVito",quote:"If it doesn’t challenge you, it doesn’t change you." ),
  QModel(author:"Jim Rohn",quote:"You can either suffer the pain of discipline or the pain of regret." ),
  QModel(author:"Simone Biles",quote:"We can push ourselves further. We always have more to give." ),
  QModel(author:"Michael Phelps",quote:"If you want to be the best, you have to do things other people aren’t willing to do." ),
  QModel(author:"Rock Balboa",quote:"Every champion was once a contender who refused to give up." ),
  QModel(author:"Marvin Phillips",quote:"The difference between try and triumph is a little ‘umph’." ),
  QModel(author:"Ray Lewis",quote:"If you are not pissed off for greatness, that just means you’re okay with being mediocre." ),
  QModel(author:"Alex Morgan",quote:"Keep working even when no one is watching." ),
  QModel(author:"Jack LaLanne",quote:"Your health account, your bank account, they’re the same thing. The more you put in, the more you can take out. Exercise is king and nutrition is queen. Together you have a kingdom." ),
  QModel(author:"Mo Farah",quote:"Don’t dream of winning. Train for it!" ),
  QModel(author:"Michael Boyle",quote:"Most people give you right before the big break comes, don’t let that person be you." ),
  QModel(author:"Jim Rohn",quote:"Discipline is the bridge between goals and accomplishment." ),
  QModel(author:"Khloe Kardashian",quote:"Fitness is not about being better than someone else. It’s about being better than you used to be." ),
  QModel(author:"Gene Tunney",quote:"Exercise should be regarded as a tribute to the heart." ),
  QModel(author:"Emily Infeld",quote:"Keep listening to your body. It will tell you when something is not okay." ),
  QModel(author:"Henry Ford",quote:"Whether you think you can, or you think you can’t. you are right" ),
  QModel(author:"Walt Disney",quote:"All our dreams can come true if we have the courage to pursue them." ),
  QModel(author:"Kobe Bryant",quote:"Great things come from hard work and perseverance. No excuses." ),
  QModel(author:"Arnold Palmer",quote:"Always make a total effort, even when the odds are against you." ),
  QModel(author:"Winston Churchill",quote:"Success is walking from failure to failure with no loss of enthusiasm." ),
  QModel(author:"Reginald Red",quote:"Your mind will quit a thousand times before your body will." ),
  QModel(author:"Serena Williams",quote:"I’ve grown most not from victories, but setbacks. If winning is God’s reward, then losing is how he teaches us." ),
  QModel(author:"Bo Jackson",quote:"Set your goals high, and don’t stop until you get there." ),
  QModel(author:"Joseph Pilates",quote:"Physical fitness can neither be achieved by wishful thinking nor outright purchase." ),
  QModel(author:"Stephen Curry",quote:"If you take time to realize what your dream is and what you really want in life — no matter what it is, whether it’s sports or in other fields — you have to realize that there is always work to do, and you want to be the hardest working person in whatever you do, and you put yourself in a position to be successful. And you have to have a passion about what you do." ),
  QModel(author:"Pavel Tsatsouline",quote:"You shall gain, but you shall pay with sweat, blood, and vomit." ),
  QModel(author:"Drew Brees",quote:"You have to push past your perceived limits, push past that point you thought was as far as you can go." ),
  QModel(author:"Hannah Gabriels",quote:"Get ready, be prepared. So when opportunities finally show themselves, you’ll be able to own them." ),
  QModel(author:"Michael Phelps",quote:"You dream. You plan. You reach. There will be obstacles. There will be doubters. There will be mistakes. But with hard work, with belief, with confidence and trust in yourself and those around you, there are no limits." ),
  QModel(author:"Dwayne ‘The Rock’ Johnson",quote:"Be Humble. Be Hungry. And always be the hardest worker in the room." ),
  QModel(author:"Michael Jordan",quote:"Some people want it to happen, some wish it would happen, others make it happen." ),
  QModel(author:"Karen Lamb",quote:"A year from now you may wish you had started today." ),
  QModel(author:"Deena Kastor",quote:"A goal is just an awesome way to force growth on yourself" ),
  QModel(author:"Kobe Bryant",quote:"If you do not believe in yourself, no one will do it for you" ),
  QModel(author:"William Shakespeare",quote:"Our bodies are gardens, our wills are our gardeners." ),
  QModel(author:"Jillian Michaels",quote:"Get comfortable with being uncomfortable!" ),
  QModel(author:"Usain Bolt",quote:"Time, Effort, Sacrifice, and Sweat. How will you pay for your goals?" ),
  QModel(author:"Muhammad Ali",quote:"He who is not courageous enough to take risks, will accomplish nothing in life." ),
  QModel(author:"Tom Hanks",quote:"It’s supposed to be hard. If it was’t hard, everyone would do it.  The hard is what makes it great." ),
  QModel(author:"Morihei Ueshiba",quote:"The purpose of training is to tighten up the slack, toughen the body, and polish the spirit." ),
  QModel(author:"Zig Ziglar",quote:"Put all excuses aside and remember this: You are capable." ),
  QModel(author:"Leigh Huntfs",quote:"The groundwork for all happiness is good health." ),
  QModel(author:"Henry David Thoreau",quote:"Success usually comes to those who are too busy to be looking for it." ),
  QModel(author:"Vidal Sassoon",quote:"The only place where success comes before work is in the dictionary." ),
  QModel(author:"Greg Plitt",quote:"The clock is ticking. Are you becoming the person you want to be?" ),
  QModel(author:"Bruce Lee",quote:"The successful warrior is the average man, with laser-like focus." ),
  QModel(author:"Lance Armstrong",quote:"Pain is temporary. Quitting lasts forever." ),
  QModel(author:"John F. Kennedy",quote:"Physical fitness is not only one of the most important keys to a healthy body, it is the basis of dynamic and creative intellectual activity." ),
  QModel(author:"Tony Robbins",quote:"No matter how many mistakes you make or how slow you progress, you are still way ahead of everyone who isn’t trying." ),
  QModel(author:"Akash",quote:"Making excuses burns zero calories per hour." ),
  QModel(author:"Ralph Waldo Emerson",quote:"The only person you are destined to become is the person you decide to be." ),
  QModel(author:"Samuel Johnson",quote:"Great works are performed, not by strength, but by perseverance." ),];